Add widgets documentation to tardis docs
tardis-sn/tardis pull request #1280
Opened 2020-08-19 14:35 UTC by jaladh-singhal

It adds documentation of widgets to tardis docs by creating a directory `tardis_widgets` having:
- `using_widgets.rst` - For description about how to use widgets and their features
- `generating_widgets.ipynb` - Demo notebook to generate widgets

2020-08-19 15:29 UTC, MarkMageeAstro commented on docs/running/tardis_widgets/using_widgets.rst
> +of a Supernova ejecta.
"of the model supernova ejecta"

2020-08-19 15:30 UTC, MarkMageeAstro commented on docs/running/tardis_widgets/using_widgets.rst
> +populates data in the table(s) right to it. All these 4 tables, in order, has
"tables to the right of it"

"Each table has the following information"

2020-08-19 15:37 UTC, MarkMageeAstro commented on docs/running/tardis_widgets/using_widgets.rst
> +(computational partitions) of a Supernova ejecta. Shell numbers in ascending
"for each cell...of the model supernova ejecta"

"Shell numbers are given in ascending order, from the innermost shell to the outermost."

2020-08-19 15:43 UTC, MarkMageeAstro commented on docs/running/tardis_widgets/using_widgets.rst
> +simulation model.
"explore the atomic lines responsible for producing features in the simulated spectrum"

2020-08-19 15:43 UTC, ycamacho commented on docs/running/tardis_widgets/using_widgets.rst
> +2. **Element Abundances** - Fractional abundance of each element present in the
Fractional (mass) abundance

2020-08-19 15:45 UTC, MarkMageeAstro commented on docs/running/tardis_widgets/using_widgets.rst
> +table of species abundances (fraction of packets interacting). Using
"display a table giving the fraction of packets that experienced their last interaction with each element."

2020-08-19 15:46 UTC, MarkMageeAstro commented on docs/running/tardis_widgets/using_widgets.rst
> +emitted or absorbed wavelengths of packets. Clicking on a row in species
"by the emitted..."

2020-08-19 15:46 UTC, ycamacho commented on docs/running/tardis_widgets/using_widgets.rst
> +3. **Ion Abundances** - Fractional abundance of each ion (species) of the
Fractional (mass) abundance

2020-08-19 15:47 UTC, jordi5 commented on docs/running/tardis_widgets/using_widgets.rst
> +
Clicking on a row in "species abundance" table reveals packet counts for each last line interaction. These packet counts can be grouped by excitation lines, de-excitation lines or both, using the dropdown (arrow?, menu?).

2020-08-19 15:47 UTC, ycamacho commented on docs/running/tardis_widgets/using_widgets.rst
> +4. **Level Abundances** - Fractional abundance of each level of the selected
Fractional (mass) abundance

2020-08-19 15:49 UTC, jordi5 commented on docs/running/tardis_widgets/using_widgets.rst
> +widths to specify range on X-axis i.e. wavelength range.
... specify range on the wavelength axis

2020-08-19 15:50 UTC, MarkMageeAstro commented on docs/running/tardis_widgets/using_widgets.rst
> +figure and the pink colored selection box will appear. If you're wondering
"drag on the figure and a pink"

I would remove the next sentence and just put: "Make a selection across the wavelength range you're interested in and the line info table will update to show only packets from this region"

2020-08-19 15:51 UTC, jordi5 commented on docs/running/tardis_widgets/using_widgets.rst
> +Since spectra are usually very long, so it makes sense to focus (horizontally
Use either "since" or "so" using both is redundant.

2020-08-19 15:52 UTC, MarkMageeAstro commented on docs/running/tardis_widgets/using_widgets.rst
> +Since spectra are usually very long, so it makes sense to focus (horizontally
I would change this paragraph to "The rangeslider is a long bar below the figure that allows you to zoom into particular wavelength regions."

2020-08-19 15:53 UTC, jordi5 commented on docs/running/tardis_widgets/using_widgets.rst
> +helpful to focus on a feature in spectrum. You can always revert back to
feature in *the* spectrum

2020-08-19 16:04 UTC, MarkMageeAstro commented on docs/running/tardis_widgets/generating_widgets.ipynb
>     "cell_type": "markdown",
<p>"TARDIS widgets that allows..."</p><p> </p><p>"This notebook represents a quick-start tutorial, but more detail on each widget (and its features) is giving in the Using TARDIS Widgets section of the documentation"</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/tardis-sn/tardis/pull/1280/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='0'/>

2020-08-19 16:04 UTC, MarkMageeAstro commented on docs/running/tardis_widgets/generating_widgets.ipynb
>     "cell_type": "markdown",
<p>TARDIS, for consistency</p><p> </p><p>"as an HDF"</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/tardis-sn/tardis/pull/1280/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='9'/>

2020-08-19 16:04 UTC, MarkMageeAstro commented on docs/running/tardis_widgets/generating_widgets.ipynb
>     "cell_type": "markdown",
<p>By selecting a wavelength range on the spectrum plot, you can see the species responsible for producing the features within that range. This is determined by counting the number of escaping packets that experienced their last interaction with each ion. Packets can be filtered by the wavelength at which they were absorbed or emitted. You can then click on each species to see the packets counts for specific lines. These can be grouped in several ways. </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/tardis-sn/tardis/pull/1280/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='11'/>

2020-09-09 14:59 UTC, jamesgillanders commented on docs/running/tardis_widgets/using_widgets.rst
> +The rangeslider is a long bar below the figure that allows you to zoom on a
...to zoom in on a...

2020-09-09 14:59 UTC, jamesgillanders commented on docs/running/tardis_widgets/using_widgets.rst
> +helpful to focus on a feature in the spectrum. You can always revert back to
... a rectangular zoom...

2020-09-09 15:00 UTC, jamesgillanders commented on docs/running/tardis_widgets/using_widgets.rst
> +helpful to focus on a feature in the spectrum. You can always revert back to
which may be helpful

2020-09-10 16:26 UTC, jamesgillanders requested changes
great work @jaladh-singhal! Very well documented. Happy for this to be merged, pending review of my comments

2020-09-17 13:10 UTC, jamesgillanders approved these changes

2020-09-24 13:24 UTC, MarkMageeAstro commented on docs/running/tardis_widgets/using_widgets.rst
> +populates data in the table(s) right of it. Each table has the following
...table(s) to the right of it.

2020-09-24 14:25 UTC, MarkMageeAstro requested changes
One minor comment regarding grammar, but otherwise looks good.

2020-09-27 20:40 UTC, MarkMageeAstro approved these changes
Looks all good to me.

2020-09-29 14:55 UTC, marxwillia approved these changes

2020-09-29 15:11 UTC, merged