Added new feature abundance vs velocity plot
tardis-sn/tardis pull request #1488
Opened 2021-03-16 14:32 UTC by sandsinghal

This is a PR to solve the first objective of the project titled "Custom Abundance Widget" for GSOC 2021
## Description

The objective required creation of a plot of abundance of elements as a function of velocity. I have made two changes in the main code to do the same:
* Created a file `abundance_vs_velocity.py` in the location `tardis\visualization\widgets\abundance_vs_velocity.py`
* Imported the definition `plot_abundance_vs_velocity` in `tardis\visualization\__init__.py`

What does it require to obtain a plot?
* Need to create a `.yml` format file or a 'csvy model` format file
* Run the simulation on the created file
* Pass the obtained simulation to the created function `plot_abundance_vs_velocity`

To run the plot need to run the following commands:
`from tardis import run_tardis`
`sim = run_tardis('any_example_file.yml')`
`from tardis.visualization import plot_abundance_vs_velocity`
`plot_abundance_vs_velocity(sim)`

Could the respective mentors provide some feedback on this task @jaladh-singhal
## Motivation and Context

## How Has This Been Tested?
- [ ] Testing pipeline
- [ ] Reference Data Comparison following these [instructions](https://tardis-sn.github.io/tardis/development/continuous_integration.html)
- [ ] Other (please describe)

## Screenshots (if appropriate):
Ran on the file radiative_csvy.yml with some modeification made. I have added few more velocity points to increase the shells from 2 to 6. I obtained the following result.
![oie_BNJsIj8x7GwQ](https://user-images.githubusercontent.com/45767605/111322156-9ea4a380-868e-11eb-953e-2d94facb20d9.png)
![oie_16145625odex0N8f(1)](https://user-images.githubusercontent.com/45767605/111322179-a7957500-868e-11eb-99ed-3239c136e147.png)

Link to the csvy model format file used is [here](https://drive.google.com/drive/folders/12Qjf9ijbcAFPLh6eMij7IUaPQyOOi0fo?usp=sharing).

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] None of the above (please describe)

## Checklist:

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [ ] I have built the documentation on my fork following [these instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html)
- [ ] I have assigned and requested two reviewers for this pull request

2021-03-16 15:30 UTC, sandsinghal commented
I am getting codecov/project error Merging #1488 (03c6a11) into master (9497250) will decrease coverage by 1.38%. Could somebody tell me how to resolve this problem.

2021-03-17 12:30 UTC, jamesgillanders commented
Can you add velocity units to the x-axis?

2021-03-17 15:49 UTC, sandsinghal commented
> Can you add velocity units to the x-axis?

I have added the units and updated the code. Please check now.

2021-03-17 22:03 UTC, marxwillia commented
@sandsinghal great work!  Can you please make another plotting function that makes the same plot, but instead uses the interactive python plotting tool plotly?

2021-03-18 18:24 UTC, sandsinghal commented
I have added a new plotting function `plotly_abundance_vs_velocity` in the same file `abundance_vs_velocity.py`. This function plots with the help of plotly. Please check now.

2021-04-05 19:54 UTC, jaladh-singhal requested changes
@sandsinghal Sorry for such delayed reply. This looks great except few comments I've mentioned.

2021-04-05 19:54 UTC, jaladh-singhal commented on tardis/visualization/widgets/abundance_vs_velocity.py
> +def atomic_number_to_element_symbol():
We already have similar function in tardis.util - you can even find other visualization modules using it

2021-04-05 19:54 UTC, jaladh-singhal commented on tardis/visualization/widgets/abundance_vs_velocity.py
> +            title="Velocity in " + str(sim.model.velocity.unit),
Format strings will be better :)

2021-04-05 19:54 UTC, jaladh-singhal commented on tardis/visualization/widgets/abundance_vs_velocity.py
> +    for index, row in df.T.iterrows():
Are you sure this is the most time-efficient way to iterate over a pandas dataframe?

2021-04-13 18:51 UTC, closed without merging