Making sponsors page of documentation
tardis-sn/tardis pull request #1584
Opened 2021-05-23 19:49 UTC by smithis7

Added a sponsors page to the documentation as can be seen [here](https://smithis7.github.io/tardis/branch/sponsor_doc/sponsors.html).

**Description**

The sponsors page includes logos for Google, ESA, and NumFOCUS.

**Motivation and context**

Wolfgang requested that this page be added to the documentation.

**How has this been tested?**
- [ ] Testing pipeline.
- [x] Other. 
Documentation build locally and on github.

**Type of change**

- [ ] Bug fix. 
- [x] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [x] My change requires a change to the documentation.
    - [x] I have updated the documentation accordingly.
    - [x] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [x] I have assigned and requested two reviewers for this pull request.

2021-05-24 15:56 UTC, jaladh-singhal requested changes
Look great - thanks @smithis7 for making this so quick!

2021-05-24 15:56 UTC, jaladh-singhal commented on docs/sponsors.rst
> +
Can you add a one-line explanation, something like "We're grateful to the following organisations for sponsoring us and helping us sustain TARDIS as a free and open source software."?

2021-05-25 12:12 UTC, jaladh-singhal approved these changes

2021-05-25 15:50 UTC, merged

2021-05-31 20:54 UTC, Molkree commented
I don't see the contents of this page in Chrome, not even the `We are grateful to the following organisations` line.

![image](https://user-images.githubusercontent.com/12860284/120241133-cc02f580-c26a-11eb-8caf-f032450daa28.png)

It's just fine in Edge.

![image](https://user-images.githubusercontent.com/12860284/120241428-6400df00-c26b-11eb-9d79-0b59f649e924.png)

2021-05-31 22:39 UTC, smithis7 commented
> I don't see the contents of this page in Chrome, not even the `We are grateful to the following organisations` line.
> 
> ![image](https://user-images.githubusercontent.com/12860284/120241133-cc02f580-c26a-11eb-8caf-f032450daa28.png)
> 
> It's just fine in Edge.
> 
> ![image](https://user-images.githubusercontent.com/12860284/120241428-6400df00-c26b-11eb-9d79-0b59f649e924.png)

That's very odd. It works fine for me in chrome. Does the page source appear correctly when you click "view page source" in chrome?

2021-06-01 13:33 UTC, Molkree commented
@smithis7, it seems so?
![image](https://user-images.githubusercontent.com/12860284/120330842-e3d38b80-c2f5-11eb-9423-4f8d4957a59e.png)

But the contents are 0px height
![image](https://user-images.githubusercontent.com/12860284/120332007-fef2cb00-c2f6-11eb-9da2-0ab7ff396841.png)

2021-06-01 14:59 UTC, Molkree commented
Okay, I see why it happens, it's AdGuard.

2021-06-01 17:47 UTC, Molkree commented
For anyone interested, AdGuard has [updated](https://github.com/AdguardTeam/AdguardBrowserExtension/issues/1815) filters so it works correctly now.