Adding Interactive Initialization Documentation
tardis-sn/tardis pull request #1589
Opened 2021-05-25 22:23 UTC by smithis7

This PR creates interactive documentation on energy packet initialization.

**Description**

The new notebook incorporates the "Discretization" page and elements of the "Propagation" page of the documentation, as well as code that demonstrates how packets are initialized in TARDIS. This PR also fixes hyperlink problems that arose from my changes.

**Motivation and context**

This is part of a larger problem to make the TARDIS documentation more interactive.

**How has this been tested?**
- [ ] Testing pipeline.
- [x] Other. 
The documentation has been built locally and on github (see below)

**Examples**

You can view the built documentation with my changes [here](https://smithis7.github.io/tardis/branch/initialization_doc/index.html).

**Type of change**

- [ ] Bug fix. 
- [x] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [x] My change requires a change to the documentation.
    - [x] I have updated the documentation accordingly.
    - [x] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [x] I have assigned and requested two reviewers for this pull request.

2021-05-27 18:19 UTC, andrewfullard commented on docs/physics/montecarlo/initialization.ipynb
> +    "conservation and constitutes the main advantage of this discretization scheme. **However, while the energy of the packets is conserved in the co-moving frame, the frequency of the contituent pho
may *vary*

2021-05-27 18:22 UTC, andrewfullard reviewed
Looks great just needs a few typos fixed

2021-05-27 18:22 UTC, andrewfullard commented on docs/physics/montecarlo/initialization.ipynb
> +    "The followig cell contains values that you can change to see how it affects the spectrum:"
following

2021-05-27 18:22 UTC, andrewfullard commented on docs/physics/montecarlo/initialization.ipynb
> +    "You can either set a temperatature of the photosphere, which will determine its luminosity; or you can set the luminosity of the photosphere, which will determine it's temperature."
its

2021-05-27 18:22 UTC, andrewfullard commented on docs/physics/montecarlo/initialization.ipynb
> +    "We define important constants, and for comparisson's sake, we code the Planck distribution function\n",
comparison's

2021-05-27 18:29 UTC, smithis7 commented
> Looks great just needs a few typos fixed

Fixed. I really need to put my writing into a spelling/grammar check program before I make a PR *insert facepalm emoji*

2021-05-27 19:44 UTC, smithis7 commented
Converted to draft until #1592 is merged so I can edit this notebook to reflect the changes to the code.

2021-06-03 13:20 UTC, andrewfullard approved these changes

2021-06-16 16:35 UTC, chvogl requested changes
This looks great! Really nice job writing up a complex topic. My only concern are some minor PEP 8 issues, which would be good to fix.

2021-06-16 16:35 UTC, chvogl commented on docs/physics/montecarlo/initialization.ipynb
> +    "conservation and constitutes the main advantage of this discretization scheme. **However, while the energy of the packets is conserved in the co-moving frame, the frequency of the contituent pho
```suggestion
    "conservation and constitutes the main advantage of this discretization scheme. **However, while the energy of the packets is conserved in the co-moving frame, the frequency of the constituent photons (in the local co-moving frame) may vary over the course of the simulation. Thus, a packet may represent several different numbers of real photons throughout their lifetimes.**\n",
```

2021-06-16 16:35 UTC, chvogl commented on docs/physics/montecarlo/initialization.ipynb
> +    "from tardis.montecarlo.packet_source import *\n",
I would avoid a star import. Just import the `BlackBodySimpleSource` (and everything else you need explicitly).

2021-06-16 16:35 UTC, chvogl commented on docs/physics/montecarlo/initialization.ipynb
> +    "n_packets = 40000 #number of packets generated"
This cell and the next few code cells have some minor PEP 8 violations. In this cell, the inline comments do not follow the guidelines: "Inline comments should be separated by at least two spaces from the statement. They should start with a # and a single space."
Maybe reformat this cell and the next few using black outside of the notebook?

2021-06-16 16:35 UTC, Rodot- commented
Try to use astropy units when instantiating quantities containing units to keep consistency with the way that constants are access from astropy.

2021-06-17 18:47 UTC, Rodot- approved these changes

2021-06-17 19:52 UTC, merged