add value error to ensure active virtual packet logging in SDECPlotter
tardis-sn/tardis pull request #1597
Opened 2021-05-31 14:42 UTC by yuyizheng1112

This PR allows SDECPlotter to raise error if `virtual_packet_logging` is not set to `True`.

**Motivation and context**

Before this change, SDECPlotter can work even when `virtual_packet_logging` is not active. In this case, an index error is raised by function in `matplotlib` while calling the function `plotter.generate_plot_mlp()`, and the output is confusing. 
Since SDECPlotter requires `virtual_packet_logging`, it should ensure the option is set to true.
**How has this been tested?**
- [ ] Testing pipeline.
- [ ] Other. 

**Examples**

Before change:
![image](https://user-images.githubusercontent.com/80535029/120209311-1a12fb80-c261-11eb-983c-8341e1c9e1d1.png)

After change:
![image](https://user-images.githubusercontent.com/80535029/120206557-ec788300-c25d-11eb-98ee-4d7ee0a5764e.png)

**Type of change**

- [ ] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [ ] I have assigned and requested two reviewers for this pull request.

2021-06-01 16:20 UTC, jamesgillanders commented
I don't understand why virtual_packet_logging needs to be set to True - I thought we left it so that we could make SDEC plots with either real or virtual packets?

2021-06-01 16:20 UTC, jamesgillanders commented
@jaladh-singhal do you know why this isn't working?

2021-06-01 21:26 UTC, wkerzendorf commented
@yuyizheng1112 can you write tests for the PR?

2021-06-02 02:58 UTC, yuyizheng1112 commented
@jamesgillanders When calling `generate_plot_mlp()` in the case of `virtual_packet_logging: False`, the function will raise the error above, and I think this can be confusing for people unfamiliar with tardis. 

I also think there is no need to set it to true for those who plot real packets only. But the instruction in `sdec_plot.ipynb` indicates that the option must set to true in order to generate SDEC plot. I did this to consist with the instruction & avoid the error raised by `generate_plot_mlp()`.

Maybe I can put this exception in function `generate_plot_mlp` instead of when generating plotter. What do you think about it?

2021-06-03 14:47 UTC, jamesgillanders commented
So can I clarify something? There should be functionality to allow the SDEC plot to generate with real packets, but that does not currently work. And this PR will print an error message to explain that the real packets mode don't work. Is that right? Then at some point, after this fix has been implemented, will we fix the real packets mode so that it does work?

2021-06-03 14:48 UTC, jamesgillanders commented
If all of that is the case, then we will have to come back and remove this fix, so that the code will allow a plot to be generated using real packets. Or am I misunderstanding the problem being addressed here?

2021-06-03 15:04 UTC, yuyizheng1112 commented
@jamesgillanders  The default value for `packets_mode` is `"virtual"` in this function, so in this case, we are plotting using virtual packets. If virtual packet is not loaded in, it will raise the confusing exception above. As for the real mode, it works well no matter the option is active or not.
Does it make sense? :)

2021-06-03 15:17 UTC, jaladh-singhal commented
> @jaladh-singhal do you know why this isn't working?

@jamesgillanders becuase there are currently no tests for SDEC plot hence test coverage is failing

2021-06-03 15:47 UTC, jaladh-singhal commented
@yuyizheng1112 @jamesgillanders I think I understand both of your reasoning. I see an intersecting solution for this problem:
- First, inside `SDECPlotter.from_simulation`, if `sim.runner.virt_logging` is False then return dictionary with `virtual=None`, otherwise keep it as it is i.e. `virtual=SDECData.from_simulation(sim, "virtual")`. 

- Then, in `_calculate_plotting_data()`, if `packets_mode` is `virtual` and `data[packets_mode]` is None then raise ValueError that "SDECPlotter doesn't have any data for virtual packets population and SDEC plot for the same was requested. Either set `virtual_packet_logging: True` in your simulation's configuration file to generate SDEC plot for virtual packets population, or pass `packets_mode="real"` in your function call to generate SDEC plot for real packets population."

This way even when virtual packets logging is not enabled, SDEC plot can still be obtained for real packets mode (what @jamesgillanders is saying) and will only give error when virtual packets mode is requested by user (what @yuyizheng1112 is trying to do).

2021-06-03 15:50 UTC, jaladh-singhal commented
> But the instruction in sdec_plot.ipynb indicates that the option must set to true in order to generate SDEC plot. I did this to consist with the instruction & avoid the error raised by generate_plot_mlp().

@yuyizheng1112 Good point! The instruction should actually be changed to "The virtual packet logging capability must be active in order to produce SDEC Plot **for virtual packets population**. Thus ..." and it should be moved right after 5th cell's output.

2021-06-03 15:53 UTC, jaladh-singhal requested changes
@yuyizheng1112 can you please change this as per my comments?

2021-06-04 08:26 UTC, yuyizheng1112 commented
@jaladh-singhal Sure. I've changed both ValueError and instruction.

2021-06-17 18:29 UTC, jaladh-singhal requested changes
Thanks for the changes @yuyizheng1112 - I had a one minor comment.

Also, I hope you've tested this for config files with vpacket logging not enabled - can you post screenshots of that?

2021-06-17 18:29 UTC, jaladh-singhal commented on tardis/visualization/tools/sdec_plot.py
> +                'SDECPlotter doesn\'t have any data for virtual packets population and SDEC plot for the same was requested.\nEither set virtual_packet_logging: True in your configuration file to gen
It's better to break long string to multiple lines following 80 char limit. Also if you use `"..."` for your string you will not need to escape `'` used inside your string - see how L575-L576 does this

2021-06-21 09:36 UTC, jaladh-singhal approved these changes
Excellent!

2021-06-21 09:40 UTC, jaladh-singhal commented on docs/io/visualization/sdec_plot.ipynb
>     "source": [
<p>There's an extra newline here that shouldn't be present</p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/tardis-sn/tardis/pull/1597/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='4'/>

2021-06-21 19:15 UTC, KevinCawley approved these changes

2021-06-22 14:41 UTC, merged