Enabling virtual_packet_logging by default in the visualization folder
tardis-sn/tardis pull request #1693
Opened 2021-07-07 04:19 UTC by atharva-2001

This PR removes the symbolic link to tardis_example.yml in the visualization folder, and adds it with `virtual_packet_logging` enabled.

**Description**

To build the SDEC plot and the Line Info widget, one needs to enable `virtual_packet_logging` from the `run_tardis` function or edit the tardis_example.yml file in the docs folder. This enables `virtual_packet_logging` by default just for the visualization folder, easing the process for the user.

**Motivation and context**

https://github.com/tardis-sn/tardis/pull/1665#pullrequestreview-697583309

**How has this been tested?**
- [X] Testing pipeline.
- [ ] Other. 

**Examples**

**Type of change**

- [X] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [ ] I have assigned and requested two reviewers for this pull request.

2021-07-07 11:54 UTC, smithis7 commented
Because of how we do things with symlinks, I think you should either:

- rename that file to something else besides `tardis_example.yml`

- add virtual packet logging to `docs/tardis_example.yml` and keep the file in `docs/io/visualization` as a symlink

2021-07-07 12:51 UTC, MarkMageeAstro commented
We can probably change to something like tardis_example_SDEC? I guess this would also mean some notebooks need updated too

2021-07-07 12:51 UTC, MarkMageeAstro requested changes
See previous comment...

2021-07-08 11:52 UTC, yuyizheng1112 commented
just a suggestion: I used to add `virtual_packet_logging` option to `run_tardis()` function (see [this pr](https://github.com/tardis-sn/tardis/pull/1498)). It seems that few people know this... Maybe you can set this option to `True` instead of adding new file.

2021-07-08 13:19 UTC, atharva-2001 commented
That sounds good to me too, maybe we could just set `virtual_packet_logging` to True in both notebooks in https://github.com/tardis-sn/tardis/pull/1665?

2021-07-08 19:57 UTC, jaladh-singhal requested changes
I think instead of adding new file, enabling virtual packet logging in run_tardis call will be better as suggested by @yuyizheng1112 .

And if you want to keep the new config file, name it as `tardis_example_virt_logging.yml` instead since it's not only for SDEC but also for Line info widget.

2021-07-22 18:51 UTC, andrewfullard commented
Is this PR still relevant?

2021-07-22 19:56 UTC, jaladh-singhal approved these changes

2021-08-19 12:19 UTC, jamesgillanders approved these changes

2021-08-19 13:26 UTC, merged