require time_0 to exist and be a astropy quantity
tardis-sn/tardis pull request #1729
Opened 2021-07-15 22:00 UTC by wkerzendorf

The decay dataframe should really require a time of definition and not just assume `time_0 = 0 * u.day` if this is not given
We also make sure that time_0 is a quantity (using ducktyping). 

**How has this been tested?**
- [x] Testing pipeline.
- [ ] Other. 

**Type of change**

- [ ] Bug fix. 
- [x] New feature. 
- [x] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [x] I have assigned and requested two reviewers for this pull request.

2021-07-16 14:15 UTC, andrewfullard commented
I think existing simple configurations need to be updated so that tests pass. Also, black has failed.

2021-08-09 15:14 UTC, afloers requested changes
I agree that the time_0 should be specified in all Tardis runs. 
Black needs to be run on the `tardis/io/decay.py` file, there were additional PEP8 violations. I fixed the ones added in this PR.
As @andrewfullard wrote tests are failing because the configurations used in the tests haven't been updated yet.

2021-08-09 15:14 UTC, afloers commented on tardis/io/decay.py
> +            time where the given isotopes are defined
black reformatting:
```suggestion
    Parameters
    ----------
    time_0 : astropy.units.Quantity
        time where the given isotopes are defined
```

2021-11-10 14:57 UTC, andrewfullard requested changes
Fix the tests :)

2022-02-23 16:19 UTC, closed without merging