Adding Convergence Plots to the Documentation
tardis-sn/tardis pull request #1753
Opened 2021-07-23 16:38 UTC by atharva-2001

This PR adds convergence plots to TARDIS documentation. 

**Description**

This PR demonstrates the convergence plots in the documentation by adding the convergence plots notebook to the toctree and rerunning the quickstart notebook. 

**Motivation and context**

**How has this been tested?**
- [ ] Testing pipeline.
- [ ] Other. 

**Examples**

**Type of change**

- [ ] Bug fix. 
- [X] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [X] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [X] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [ ] I have assigned and requested two reviewers for this pull request.

2021-07-26 14:14 UTC, smithis7 requested changes
Make sure you clear the output in the quickstart notebook

2021-07-26 16:30 UTC, jaladh-singhal approved these changes

2021-07-27 14:06 UTC, smithis7 approved these changes

2021-07-29 18:56 UTC, jaladh-singhal approved these changes

2021-07-29 18:57 UTC, merged