Fix Virtual Packet Logging Bug
tardis-sn/tardis pull request #1846
Opened 2021-12-19 08:14 UTC by atharva-2001

Resolves https://github.com/tardis-sn/tardis/issues/1764

**Description**

The `montecarlo_configuration.VPACKET_LOGGING` in the `montecarlo_main_loop` function was being cached.
This prevented variables related to virtual packets from populating and raised an error. Passing `virtual_packet_logging` in the `montecarlo_main_loop` function fixes this.

https://github.com/tardis-sn/tardis/blob/f24be9aeae96c1f3b8af7e7fd91ac700a5d3c9d1/tardis/montecarlo/montecarlo_numba/base.py#L280-L328

**Motivation and context**

Resolves https://github.com/tardis-sn/tardis/issues/1764 and partially solves failing SDEC tests problem https://github.com/tardis-sn/tardis/pull/1752 

**How has this been tested?**
- [ ] Testing pipeline.
- [ ] Other. 

**Examples**

**Type of change**

- [ ] Bug fix. 
- [ ] New feature. 
- [ ] Breaking change. 
- [ ] None of the above. 

**Checklist**

- [ ] My change requires a change to the documentation.
    - [ ] I have updated the documentation accordingly.
    - [ ] (optional) I have built the documentation on my fork following [the instructions](https://tardis-sn.github.io/tardis/development/documentation_preview.html).
- [ ] I have assigned and requested two reviewers for this pull request.

2021-12-20 15:18 UTC, andrewfullard approved these changes

2021-12-20 15:18 UTC, andrewfullard requested changes
Please update the docstring for `montecarlo_main_loop`. You don't need to document all the other inputs, just the one you've added.

2021-12-22 15:15 UTC, jaladh-singhal approved these changes

2022-01-06 15:59 UTC, andrewfullard approved these changes

2022-01-06 15:59 UTC, merged