printing packet information
tardis-sn/tardis pull request #1877
Opened 2022-01-25 21:56 UTC by wkerzendorf

when the MC crashes with diff nu < 0

2022-01-25 21:57 UTC, andrewfullard commented on tardis/montecarlo/montecarlo_numba/r_packet.py
> +def print_r_packet_properties(r_packet):
docstring

2022-01-26 16:47 UTC, wkerzendorf commented on tardis/montecarlo/montecarlo_numba/r_packet.py
> +def print_r_packet_properties(r_packet):
😝

2022-01-26 21:55 UTC, andrewfullard approved these changes

2022-01-26 21:59 UTC, andrewfullard requested changes
njit missing from import

2022-01-27 12:53 UTC, afloers commented on tardis/montecarlo/montecarlo_numba/r_packet.py
> +    print("-"*80)
```suggestion
    print("-"*80)
    
```

2022-01-27 22:14 UTC, andrewfullard approved these changes

2022-01-27 22:15 UTC, merged