Update Jsonschema package to V4
tardis-sn/tardis pull request #2050
Opened 2022-06-11 18:54 UTC by rohithvarma3000

### :pencil: Description

**Type:** :beetle: `bugfix`

Write a complete description of your changes, including the necessary context or any piece of information required to understand your work.

Also, link issues affected by this pull request by using the keywords: `close`, `closes`, `closed`, `fix`, `fixes`, `fixed`, `resolve`, `resolves` or `resolved`. 

Attempt to update the jsonschema package to v4 and handle the new bugs introduced. [Link](https://github.com/tardis-sn/tardis/issues/1807) to issue.

### :pushpin: Resources

Examples, notebooks, and links to useful references.
https://python-jsonschema.readthedocs.io/en/v3.2.0/validate/#the-validator-interface

### :vertical_traffic_light: Testing

How did you test these changes?

- [x] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [x] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

2022-06-15 19:37 UTC, rohithvarma3000 commented
I have put the extra yaml file for now so that it can be used to test the PR. I will remove it before the PR merges

2022-06-15 19:37 UTC, andrewfullard commented
Good work on the validator. However, the environment file should be merged with the existing one unless somebody told you otherwise

2022-06-15 19:47 UTC, andrewfullard requested changes

2022-06-15 19:47 UTC, andrewfullard commented on tardis/io/config_validator.py
> +    return isinstance(instance, Quantity)
Add a short docstring

2022-06-15 20:02 UTC, epassaro commented
@rohithvarma3000 You also need to render both lockfiles by installing `conda-lock` and doing `conda lock render conda-lock.yml`.

Push both lockfiles to this pull request and see if tests pass. As you can see, the [`tests.yml`](https://github.com/tardis-sn/tardis/blob/master/.github/workflows/tests.yml#L68) workflow runs tests in an environment made with the lockfiles.

2022-06-16 16:23 UTC, rohithvarma3000 commented on tardis/io/config_validator.py
> +    return isinstance(instance, Quantity)
Added the docstring.

2022-06-16 16:31 UTC, rohithvarma3000 commented
@epassaro I have regenerated the lockfiles and pushed them to the branch.

2022-06-20 14:20 UTC, andrewfullard commented
The lockfile has had a `win-64` platform added. Was this intentional? We don't officially support Windows right now. @epassaro this is potentially a problem.

2022-06-22 17:23 UTC, epassaro commented
> The lockfile has had a `win-64` platform added. Was this intentional? We don't officially support Windows right now. @epassaro this is potentially a problem.

Hi @rohithvarma3000, check the `pre-release.yml` workflow and look for the correct command to lock files only for linux/osx and then render again

2022-06-23 06:27 UTC, rohithvarma3000 commented
Thanks for the suggestion @epassaro. I have made the necessary changes to the PR.

2022-06-23 14:37 UTC, epassaro approved these changes

2022-06-23 14:37 UTC, epassaro commented
This looks good to me @andrewfullard , I approved the pull request.

2022-06-24 14:55 UTC, merged