Model State Restructure based on new design
tardis-sn/tardis pull request #2098
Opened 2022-07-18 11:31 UTC by code-explorer

### :pencil: Description

**Type:**  :rocket: `restructure`

New model state with composition and geometry classes.

### :pushpin: Resources

![New Model State Design](https://user-images.githubusercontent.com/18657672/179502328-cdb5f8ee-22bd-41b5-805a-55bdd7f53bd8.png)

2022-07-21 15:02 UTC, wkerzendorf commented
Just do the composition in this one. One PR one idea.

2022-07-22 14:38 UTC, wkerzendorf commented on tardis/model/base.py
> +        self.composition_df.index.name = "cell"
that is not needed for now.

2022-07-22 14:39 UTC, wkerzendorf commented on tardis/model/base.py
> +        return self.composition_df
or that.

2022-07-25 14:38 UTC, Rodot- requested changes

2022-07-25 14:38 UTC, Rodot- commented on tardis/model/tests/test_base.py
> +def composition_from_config(atomic_data_fname):
Use the verysimple simulation fixture instead of creating your own simulation

2022-07-25 14:38 UTC, Rodot- commented on tardis/model/base.py
> +        self.atomic_mass = atomic_mass
Add atomic_mass_unit as an additional atrtibute

2022-07-25 14:38 UTC, Rodot- commented on tardis/model/base.py
> +        self.abundance = abundance
Change name of `abundance` to `isotopic_mass_fraction`

Add a new `@property` called `elemental_mass_fraction` which groups all of the isotopes by atomic number and adds up their respective mass fractions

2022-07-25 14:38 UTC, Rodot- commented on tardis/model/tests/test_base.py
> +
Use hard-coded numbers for comparison using pytest.mark.parameterize.

2022-07-25 14:38 UTC, Rodot- commented on tardis/model/base.py
> +        self.abundance = abundance
Use the class in io/decay to represent isotopic mass fractions

2022-07-25 14:41 UTC, andrewfullard commented on tardis/model/tests/test_base.py
> +def test_composition_number_density(composition_from_config):
The expected values here should be in reference data rather than calculated in the test

2022-07-25 14:41 UTC, andrewfullard commented on tardis/model/base.py
> +    density : astropy.units.quantity.Quantity
Could use information about the shape of these arrays/dataframes

2022-08-01 14:11 UTC, andrewfullard submitted a review, later dismissed

2022-08-01 15:42 UTC, wkerzendorf commented on tardis/model/base.py
> +        self._atomic_mass = atomic_mass
why is this a private attribute?

2022-08-03 23:57 UTC, wkerzendorf commented on tardis/model/base.py
> +        self.atomic_mass = atomic_mass.to_numpy() * self.atomic_mass_unit
you shouldn't convert to an array because you need the index.

2022-08-05 14:05 UTC, wkerzendorf commented on tardis/model/base.py
> +    def number_density(self):
```suggestion
    def elemental_number_density(self):
```

2022-08-05 15:20 UTC, andrewfullard approved these changes

2022-08-08 14:36 UTC, AlexHls requested changes

2022-08-08 14:36 UTC, AlexHls commented on tardis/model/base.py
> +        self.atomic_mass_unit = u.g
You should expose this property as a keyword argument in the __init__ args.

2022-08-08 14:40 UTC, AlexHls approved these changes

2022-08-09 12:03 UTC, Rodot- approved these changes

2022-08-09 12:04 UTC, merged