New geometry class
tardis-sn/tardis pull request #2103
Opened 2022-07-22 10:56 UTC by code-explorer

### :pencil: Description

**Type:** ::rocket: `restructure` 

New geometry class for model state restructure.

### :pushpin: Resources

![Model State Plan](https://user-images.githubusercontent.com/18657672/179502328-cdb5f8ee-22bd-41b5-805a-55bdd7f53bd8.png)

2022-07-25 14:46 UTC, Rodot- requested changes

2022-07-25 14:46 UTC, Rodot- commented on tardis/model/base.py
> +    radius : astropy.units.quantity.Quantity
Give this the properties `r_inner`, `r_outer`, `v_inner`, and `v_outer` as numpy arrays containing units

2022-07-25 14:46 UTC, Rodot- commented on tardis/model/base.py
> +class Geometry:
For now, just make a class called `Radial1DGeometry` which will eventually inherit from a Geometry parent class.  The `Radial1DGeometry` should contain the attributes needed to run tardis with a radial 1D geometry

2022-07-25 14:46 UTC, Rodot- commented on tardis/model/base.py
> +    radius : astropy.units.quantity.Quantity
Make sure it has methods to compute volumes in each shell

2022-07-29 14:19 UTC, andrewfullard requested changes

2022-07-29 14:19 UTC, andrewfullard commented on tardis/model/base.py
> +    Holds information about model geometry
Be specific about the geometry type

2022-07-29 14:19 UTC, andrewfullard commented on tardis/model/base.py
> +            {"radius": radius, "velocity": velocity}
Dataframes can't read astropy quantities, so they need to be explicitly set to CGS units with the `.to_cgs` method and then converted to a pure numpy array with the `.value` method.

2022-08-01 15:16 UTC, andrewfullard commented on tardis/model/base.py
> +        self.geometry_df = pd.DataFrame(
To be clear, we have decided to cut the dataframe step. Then the class can just have `self.radius` and `self.velocity`. The properties can remain, they are just created without the dataframe. `self.radius` and `self.velocity` can keep their astropy quantities as a result, you can just use `to(u.cm)` for example.

2022-08-03 15:30 UTC, wkerzendorf commented on tardis/model/base.py
> +    def __init__(self, radius, velocity):
the call signature should be `def __init__(self, r_inner, r_outer, v_inner, v_outer):`

2022-08-05 15:19 UTC, andrewfullard approved these changes

2022-08-08 14:19 UTC, Rodot- commented on tardis/model/base.py
> +    radius : astropy.units.quantity.Quantity
Make sure the description of the doc-string matches the parameters of the __init__

2022-08-08 14:29 UTC, AlexHls submitted a review, later dismissed

2022-08-08 20:02 UTC, andrewfullard approved these changes

2022-08-09 12:05 UTC, Rodot- submitted a review, later dismissed

2022-08-09 14:54 UTC, wkerzendorf approved these changes

2022-08-10 15:32 UTC, andrewfullard approved these changes

2022-08-10 15:50 UTC, AlexHls approved these changes

2022-08-10 15:59 UTC, Rodot- approved these changes

2022-08-10 15:59 UTC, merged