made the timo_0 in decay framework required
tardis-sn/tardis pull request #2183
Opened 2022-12-29 07:38 UTC by Soumya624

### :pencil: Description

**Type:** :beetle: `bugfix` | :rocket: `feature` 

Changed the current init method in line 11 of "\tardis\io\decay.py" file, to resolve the issue. Here is a snippet of the modified version of the init method that includes a check to ensure that the time_0 parameter is specified by the user:

![Screenshot 2022-12-29 011009](https://user-images.githubusercontent.com/63846042/209918984-7d91a98a-672d-4c83-a3e0-17ef03ac878e.jpg)

This modified version first checks if the time_0 parameter is included in the kwargs dictionary. If it is not, it raises a ValueError to inform the user that the time_0 parameter must be specified. If the time_0 parameter is present, it is extracted from the kwargs dictionary and assigned to the time_0 variable. The time_0 key is then removed from the kwargs dictionary before calling the parent class's init method. Finally, the value of time_0 is assigned to the time_0 attribute of the IsotopeAbundance instance.

Also, link issues affected by this pull request by using the keywords: `close`, `closes`, `closed`, `fix`, `fixes`, `fixed`, `resolve`, `resolves` or `resolved`. 

### :pushpin: Resources

Examples, notebooks and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing Locally

![Screenshot 2022-12-29 012543](https://user-images.githubusercontent.com/63846042/209918430-cbeca4f0-db06-4334-9e14-ee0a00d4e751.jpg)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

2023-02-01 16:16 UTC, Rodot- commented
This seems to break the tests.

2023-02-01 16:22 UTC, sonachitchyan commented
> This seems to break the tests.

The tests probably assume that the "default value" is set to 0, as it was in previously. @Soumya624 , can you look into that?

2023-02-11 22:02 UTC, Soumya624 commented
Yeah sure!

2023-02-20 15:06 UTC, andrewfullard commented
@Soumya624 do you plan to address the currently failing checks soon?

2023-02-27 11:38 UTC, AyushiDaksh commented
@Soumya624 Are you still working on resolving this? If not, please let me know if I can take it forward from here.

2023-02-28 19:29 UTC, Soumya624 commented
> The tests probably assume that the "default value" is set to 0, as it was in previously

@andrewfullard  I was going through the entire repository and i found that any test cases that create an instance of the IsotopeAbundance class without explicitly specifying the time_0 parameter are likely to fail.

So, I searched the test cases and found that if we can modify 'tardis/io/tests/test_decay.py' and 'tardis/model/tests/test_base.py', then we can omit these.

To modify the simple_abundance_model() fixture in tardis/io/tests/test_decay.py to avoid the failure due to the time_0 parameter not being specified, we can add an explicit time_0 parameter with a default value of 0 to the function definition and pass this default value to the constructor of IsotopeAbundances.

@pytest.fixture
def simple_abundance_model(time_0=0):
    index = pd.MultiIndex.from_tuples(
        [(28, 56)], names=["atomic_number", "mass_number"]
    )
    return IsotopeAbundances([[1.0, 1.0]], index=index, time_0=time_0)

And to modify the simple_isotope_abundance() function in tardis/model/tests/test_base.py, we can add a similar explicit time_0 parameter with a default value of 0 to the function definition and pass this default value to the constructor of IsotopeAbundances.

def simple_isotope_abundance(time_0=0):
    index = pd.MultiIndex.from_tuples(
        [(6, 14), (12, 28)], names=["atomic_number", "mass_number"]
    )
    abundance = [[0.2] * 20] * 2
    return IsotopeAbundances(abundance, index=index, time_0=time_0)

Please let me know if this approach is correct. I will made the PR!

2023-02-28 19:30 UTC, Soumya624 commented
> @Soumya624 Are you still working on resolving this? If not, please let me know if I can take it forward from here.

@AyushiDaksh  Yeah i'm about to make a PR. With the necessary changes in the test cases!

2023-03-15 14:04 UTC, andrewfullard commented
Sorry for the late response. I think your solution is sensible, please commit it to this PR.

2023-03-27 05:30 UTC, AyushiDaksh commented
@Soumya624  Are you still working on this?

@andrewfullard If @Soumya624 is not actively working on this, then I'll take this up. In that case, would I have to make a new PR or append my changes to this PR?

2023-03-27 06:59 UTC, Soumya624 commented
Hi @andrewfullard, 
Please have a look at this now. I think tests are getting passed!

Thanks

2023-03-27 07:12 UTC, Soumya624 commented
> @Soumya624 Are you still working on this?
Yeah.  think rn it's passing the tests. Thanks for reminding!

2023-03-27 16:04 UTC, andrewfullard commented
Please resolve the merge conflict

2023-04-05 22:06 UTC, andrewfullard requested changes

2023-04-05 22:06 UTC, andrewfullard commented on tardis/io/tests/test_decay.py
> +def simple_abundance_model(x=0):
Use a more descriptive variable name than "x"

2023-04-05 22:06 UTC, andrewfullard commented on tardis/model/base.py
> +    def from_config(cls, config, atom_data=None, x=0):
See previous comment regarding variable name.

2023-04-05 22:06 UTC, andrewfullard commented on tardis/model/tests/test_base.py
> +def simple_isotope_abundance(x=0):
Again, variable name.

2023-04-10 17:57 UTC, Soumya624 commented
Hi @andrewfullard ,

Thanks for your review regarding the variable name. Please have a look at this now!

2023-04-10 19:09 UTC, andrewfullard approved these changes

2023-08-18 13:49 UTC, andrewfullard commented
@wkerzendorf do we want to require "time_0" now that we are changing how the model is set up?

2024-04-12 14:14 UTC, andrewfullard commented
Closing this in favour of later configuration restructure

2024-04-12 14:14 UTC, closed without merging