Adding doppler factor function for nonhomologous expansion
tardis-sn/tardis pull request #2374
Opened 2023-07-31 15:11 UTC by sonachitchyan

### :pencil: Description

**Type:** :beetle: `bugfix` | :rocket: `feature` | :biohazard: `breaking change` | :vertical_traffic_light: `testing` | :memo: `documentation` | :roller_coaster: `infrastructure`

Adding an alternative version of doppler factor that uses v and mu instead of r, mu and t_exp. This will be used in the nonhomologous expansion case.

Also, link issues affected by this pull request by using the keywords: `close`, `closes`, `closed`, `fix`, `fixes`, `fixed`, `resolve`, `resolves` or `resolved`. 

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [x] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [x] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

2023-08-01 21:44 UTC, DeerWhale commented
Quick question, how does `ENABLE_FULL_RELATIVITY` argument in` tardis.montecarlo.montecarlo_numba.numba_config` get updated from the initial yml file?

2023-08-02 14:10 UTC, atharva-2001 requested changes

2023-08-02 14:10 UTC, atharva-2001 commented on tardis/transport/frame_transformations.py
> +    """
Return doctring

2023-08-02 14:10 UTC, atharva-2001 commented on tardis/transport/frame_transformations.py
> +    inv_c = 1 / C_SPEED_OF_LIGHT
return docstring

2023-08-03 19:31 UTC, andrewfullard approved these changes

2023-08-14 18:28 UTC, jvshields commented
Why do there need to be entirely different functions for doppler factor and inverse doppler factor? Is there a reason you can't just calculate the number and then divide by it when appropriate?

2023-08-21 14:16 UTC, chvogl reviewed
The PR looks good. We need similar functions (that take v, mu) for the angle aberration. You could add them to this PR or make an issue. Finally, I wonder if we really want to have two set of functions for the doppler factors (normal and non-homologous). Maybe we should just use the new ones and always pass in the velocity.

2024-03-11 14:26 UTC, andrewfullard commented
@sonachitchyan do you have time to clean this up (resolve conflicts, respond to comments)?

2024-03-11 20:21 UTC, sonachitchyan commented
> @sonachitchyan do you have time to clean this up (resolve conflicts, respond to comments)?

@andrewfullard I'm not sure if we want this after the restructure.

2024-03-11 20:39 UTC, closed without merging