add isotopic_number_density
tardis-sn/tardis pull request #2609
Opened 2024-05-06 20:13 UTC by wkerzendorf

2024-05-11 16:24 UTC, Knights-Templars commented
docstrings?

2024-05-20 14:22 UTC, wkerzendorf commented on tardis/opacities/macro_atom/base.py
> +        util.calculate_transition_probabilities(
still draft I think

2024-05-20 14:24 UTC, jvshields commented
Would be nice for the refactor pr to be separate from the functional code change pr.

2024-05-23 12:58 UTC, wkerzendorf commented on tardis/opacities/tau_sobolev.py
> +        return calculate_sobolev_line_opacity(
ultimately this will be restructured completely in the future but for now I'm just carving parts for the plasma

2024-05-23 12:59 UTC, wkerzendorf commented on tardis/opacities/tau_sobolev.py
> +        return calculate_sobolev_line_opacity(
@jvshields requested that I put this back into its original form and that this PR is only a restructure.

2024-06-06 19:49 UTC, wkerzendorf commented
@andrewfullard - I believe this is based on the transport refactor, right?

2024-06-09 13:59 UTC, wkerzendorf commented on tardis/opacities/macro_atom/base.py
> +        util.calculate_transition_probabilities(
not my change - but I'll have a look

2024-06-09 20:46 UTC, wkerzendorf commented on tardis/opacities/macro_atom/base.py
> +    def _normalize_transition_probabilities(self, transition_probabilities):
I don't think it is in util. Can yiu check. I think it doesn't work but is never tested.

2024-06-10 13:55 UTC, andrewfullard commented on tardis/opacities/macro_atom/base.py
> +    def _normalize_transition_probabilities(self, transition_probabilities):
On `master` it points at `macro_atom` but the function is not defined or used anywhere. So you could just delete it.

2024-06-10 13:56 UTC, andrewfullard commented on tardis/opacities/macro_atom/util.py
> +H_CGS = const.h.cgs.value
Are any of these constants used? They are defined in other locations in tardis as well.

2024-06-10 14:12 UTC, wkerzendorf commented on tardis/opacities/opacity_state.py
> +        # Destination level is not needed and/or generated for downbranch
I'll make an issue

2024-06-10 14:13 UTC, wkerzendorf commented on tardis/opacities/tau_sobolev.py
> +):
docstr

2024-06-10 14:13 UTC, andrewfullard commented on tardis/opacities/tau_sobolev.py
> +    ):
docstr

2024-06-10 14:14 UTC, wkerzendorf commented on tardis/opacities/macro_atom/base.py
> +    def _normalize_transition_probabilities(self, transition_probabilities):
remove

2024-06-10 14:14 UTC, andrewfullard commented
run black on file

2024-06-10 14:16 UTC, andrewfullard requested changes
Add docstrings, check constant usage, run black

2024-06-19 20:26 UTC, wkerzendorf commented
> Add docstrings, check constant usage, run black, make issue re: opacitystate

I think resolved.

2024-06-21 14:12 UTC, andrewfullard approved these changes

2024-06-21 14:14 UTC, jvshields approved these changes

2024-06-21 14:14 UTC, merged