Line interaction radius Plot
tardis-sn/tardis pull request #2651
Opened 2024-06-10 11:39 UTC by sarthak-dv

### :pencil: Description

**Type:** :rocket: `feature`

This PR is part of the Velocity Packet Tracker Visualisation tool. It introduces a new Python script interaction_radius_plot.py containing the InteractionRadiusPlotter class and a Jupyter notebook interaction_radius_plot.ipynb to demonstrate accessing the class and visualizing the plot.
The plots are generated using both Matplotlib and Plotly.

This PR aims to discuss and finalize the look and feel of the Last Interaction Radius plot.

Matplotlib:
![mpl](https://github.com/tardis-sn/tardis/assets/73549869/a2ce44aa-7877-4a2e-b612-29a18d0adf82)

Plotly:
![plotly](https://github.com/tardis-sn/tardis/assets/73549869/d939a7c5-0fd1-46d9-9598-268799a163cf)

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

2024-06-11 15:33 UTC, MarkMageeAstro commented
Nice work Sarthak, the plot seems to be coming along nicely. 

I think we should have a consistent style across both matplotlib and plotly -- they should both look as close as possible to each other. I prefer the style of the current plotly version so I would try and update the matplotlib version to match it. Although I would also use a step plot for both rather than filled histograms. I prefer steps to filled because in the filled histograms you can get overlapping, translucent colours and that means they might not exactly match what's shown in the legend.

2024-06-12 10:31 UTC, sarthak-dv commented
Thanks, @MarkMageeAstro for the feedback!
I'll implement the changes to ensure that Matplotlib matches the current Plotly style, and I'll switch both to use step plots instead of filled histograms.

2024-06-12 15:30 UTC, MarkMageeAstro commented
Rather than specifying bins as an integer in your hist function, you can give it a list of values. I'm not sure exactly what the right parameter name will be, but there will be some property like self.velocity or self.simulation_state.velocity, something like that. It should give you an array of the inner and outer boundaries of the cells in the model that you can pass to hist. This way you can be sure the plot lines up exactly with the cells in the model for all elements

2024-06-14 10:29 UTC, sarthak-dv commented
@MarkMageeAstro @jamesgillanders  I have generated step plots in both Plotly and Matplotlib, adjusted the bins based on the velocity array. Please review them and confirm if they meet your expectations.

Matplotlib:

![matplotlib(step)](https://github.com/tardis-sn/tardis/assets/73549869/21b52d2e-3d51-49de-89da-d1ccba8b5c21)


Plotly:

![plotly(step)](https://github.com/tardis-sn/tardis/assets/73549869/16108019-b7c0-4107-9bf5-98edc1491a70)

2024-06-19 03:54 UTC, jaladh-singhal requested changes
Excellent work @sarthak-dv - this is coming along really nicely. I'm glad to see that you have already modularised the code along with docstrings and code comments!

I have few more suggestions to make it better - to minimize redundancy between this and SDECPlotter. Don't hesitate in exposing SDECPlotter's method if needed here. Just make sure to test that you didn't break it in doing so :)

Additional comments:
- you can move your demo notebook to docs/ with other visualisation demos
- good next step will be to start writing tests for your module

Thanks for keeping up the code quality - the variable names are also great!

2024-06-19 03:54 UTC, jaladh-singhal commented on tardis/visualization/tools/interaction_radius_plot.py
> +            ),
time_explosion, velocity needs to be passed in this instantiation too?

2024-06-19 03:54 UTC, jaladh-singhal commented on tardis/visualization/tools/interaction_radius_plot.py
> +import plotly.graph_objects as go
[nitpick] a good practice is to group imports in the follow following pattern:

imports from other packages

imports from local package (tardis)

2024-06-19 03:54 UTC, jaladh-singhal commented on tardis/visualization/tools/interaction_radius_plot.py
> +    def _parse_species_list(self, species_list):
we already have similar/same method in SDEC plot. why not make that public and generalize it if needed and share methods in these two classes

2024-06-19 03:54 UTC, jaladh-singhal commented on tardis/visualization/tools/interaction_radius_plot.py
> +    def _make_colorbar_labels(self):
same here

2024-06-19 03:54 UTC, jaladh-singhal commented on tardis/visualization/tools/interaction_radius_plot.py
> +    def _make_colorbar_colors(self):
same here

2024-06-19 03:54 UTC, jaladh-singhal commented on tardis/visualization/tools/interaction_radius_plot.py
> +            List of species to plot. Default is None.
There's no benefit of setting default here because you are raising ValueError for None, it should be a required parameter instead.

2024-06-19 03:54 UTC, jaladh-singhal commented on tardis/visualization/tools/interaction_radius_plot.py
> +        species_list : list of str
same here

2024-06-19 03:54 UTC, jaladh-singhal commented on tardis/visualization/tools/interaction_radius_plot.py
> +            color = f"rgba({int(255*self._color_list[species_counter][0])}, {int(255*self._color_list[species_counter][1])}, {int(255*self._color_list[species_counter][2])}, 1)"
there's `to_rgb255_string` in SDECPlotter, you can use that here and maybe move that staticmethod to plot_util and use in both classes.

2024-06-19 03:54 UTC, jaladh-singhal commented on tardis/visualization/tools/interaction_radius_plot.py
> +            yaxis=dict(tickformat=".1e"),
can you adjust tickformat for x-axis too to make it similar to mpl (or exponent if not possible) - we never want "1k, etc." in scientific plots

2024-06-19 03:54 UTC, jaladh-singhal commented on tardis/visualization/tools/interaction_radius_plot.py
> +            template="plotly_white",
changing template isn't necessary - we keep it default and allow user to change it if needed - see convergence plots for example

2024-06-24 07:53 UTC, closed without merging