Refactor benchmarks
tardis-sn/tardis pull request #2722
Opened 2024-07-22 13:15 UTC by officialasishkumar

### :pencil: Description

**Type:** :beetle: `bugfix` 

- fix the benchmark action of PR
- changed the name of the classes and files
- removed the benchmarks which are not important. 

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

2024-07-22 13:19 UTC, andrewfullard commented on benchmarks/transport_montecarlo_formal_integral_p.py
Why is this called `formal_integral_p`?

2024-07-22 13:19 UTC, andrewfullard commented on benchmarks/transport_montecarlo_formal_integral_p.py
> +                    "temperature": 1,
These aren't physical, I don't think they are worth parametrizing

2024-07-22 13:20 UTC, andrewfullard commented on benchmarks/transport_montecarlo_formal_integral_p.py
> +                    "temperature": 1,
Same here

2024-07-22 13:20 UTC, andrewfullard commented on benchmarks/transport_montecarlo_formal_integral_p.py
> +                    "temperature": 1e4,
This is okay

2024-07-22 13:22 UTC, officialasishkumar commented on benchmarks/transport_montecarlo_formal_integral_p.py
The `_p` was initially for the parallelism thing. I have removed it now.

2024-07-22 13:53 UTC, officialasishkumar commented
Action run: https://github.com/officialasishkumar/tardis/actions/runs/10041925413/job/27751118212?pr=53

2024-07-22 15:38 UTC, officialasishkumar commented
The benchmark run is successful in these changes. 

link: https://paste.opensuse.org/pastes/0e80fd45e5c1

2024-07-22 15:45 UTC, andrewfullard commented
I notice the before and after commits are still the same in the bot comment. Should that have been resolved here?

2024-07-23 11:08 UTC, officialasishkumar commented
yes

2024-07-24 13:20 UTC, officialasishkumar commented
new action run on the existing benchmarks.yml -> https://github.com/officialasishkumar/tardis/actions/runs/10077232306/job/27859281972

2024-07-24 13:31 UTC, officialasishkumar commented
I have ironed out all the bugs. So this can be merged to get the benchmarks working. 

cc: @andrewfullard

2024-07-24 13:42 UTC, andrewfullard requested changes
Good job fixing the benchmarks, please remove the test items

2024-07-24 13:42 UTC, andrewfullard commented on tardis/transport/montecarlo/single_packet_loop.py
> +        print("hello")
Please remove this

2024-07-24 13:42 UTC, andrewfullard commented on tardis/transport/montecarlo/single_packet_loop.py
> +import time
Please remove this

2024-07-24 13:43 UTC, officialasishkumar commented on tardis/transport/montecarlo/single_packet_loop.py
> +        print("hello")
sorry, my bad. I will fix it.

2024-07-24 13:49 UTC, andrewfullard commented on tardis/transport/montecarlo/single_packet_loop.py
> +
Excess line change

2024-07-24 13:49 UTC, officialasishkumar commented on tardis/transport/montecarlo/single_packet_loop.py
> +import time
removed

2024-07-24 13:49 UTC, officialasishkumar commented on tardis/transport/montecarlo/single_packet_loop.py
> +        print("hello")
removed

2024-07-24 13:50 UTC, officialasishkumar commented on tardis/transport/montecarlo/single_packet_loop.py
> +
removed

2024-07-24 13:53 UTC, andrewfullard approved these changes

2024-07-25 12:14 UTC, merged