[WIP] Cache benchmark functions
tardis-sn/tardis pull request #2749
Opened 2024-07-26 16:55 UTC by officialasishkumar

### :pencil: Description

**Type:**  :rocket: `feature` 

- Cache benchmark properties
- use setup functions to reduce noise

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

2024-07-26 16:55 UTC, officialasishkumar commented
I will add more updates to this PR in the next 2 days.

2024-07-29 12:57 UTC, officialasishkumar commented
I will share the action run in a couple of hours. 

Will update this comment.

2024-07-31 17:53 UTC, andrewfullard requested changes
Please resolve the file conflict

2024-07-31 17:53 UTC, andrewfullard commented on .github/workflows/benchmarks.yml
> -      contains(github.event.pull_request.labels.*.name, 'benchmarks')))
Is this delete intended?

2024-07-31 18:22 UTC, officialasishkumar commented
action run: https://github.com/officialasishkumar/tardis/actions/runs/10185546450/job/28175343352

2024-07-31 18:48 UTC, officialasishkumar commented
https://github.com/officialasishkumar/tardis/actions/runs/10185827591/job/28176215185

2024-07-31 19:00 UTC, andrewfullard commented
> https://github.com/officialasishkumar/tardis/actions/runs/10185827591/job/28176215185

Unfortunately there seem to be some failures. Definitely faster though, and actually has uncertainties reported.

2024-07-31 19:02 UTC, officialasishkumar commented
Failures in the sense?

2024-07-31 19:03 UTC, officialasishkumar commented
Oh i see. Will fix the failing benchmarks tomorrow morning.

2024-08-01 05:43 UTC, officialasishkumar commented
https://github.com/officialasishkumar/tardis/actions/runs/10192086656/job/28194385676

Changes to the master are made by merging a branch that is on top of this branch.

2024-08-01 16:31 UTC, andrewfullard submitted a review, later dismissed
Looks good, well done

2024-08-02 15:49 UTC, DeerWhale commented on benchmarks/transport_montecarlo_interaction.py
> +    def setup(self):
does this setup function also meant to have the `@functools.cache` decorator?

2024-08-02 16:47 UTC, andrewfullard approved these changes

2024-08-02 16:48 UTC, DeerWhale approved these changes

2024-08-02 18:10 UTC, andrewfullard commented
Do you know why one of the benchmarks is failing @officialasishkumar ?

2024-08-02 18:13 UTC, officialasishkumar commented
In tardis or my fork?

2024-08-02 18:38 UTC, officialasishkumar commented
Not sure why it's failing here. 

I quickly tested it in my fork by running it on that function and it works. 

PR: https://github.com/officialasishkumar/tardis/pull/82
Action: https://github.com/officialasishkumar/tardis/actions/runs/10220375847/job/28280596608

@andrewfullard

2024-08-02 18:52 UTC, officialasishkumar commented
I started another runner after merging the latest changes. 

https://github.com/officialasishkumar/tardis/actions/workflows/benchmarks.yml

2024-08-02 19:48 UTC, merged

2024-08-06 11:45 UTC, afloers commented on benchmarks/opacities_opacity.py
> +        energy = 255.9
255 (I guess keV?) for pair creation?

2024-08-06 11:47 UTC, afloers commented on benchmarks/opacities_opacity.py
> +        energy = 255.9
on which basis are these values chosen? 100000.009 seems to be quite specific

2024-08-06 11:48 UTC, afloers commented on benchmarks/opacities_opacity.py
> +        energy = 511.0
511keV is quite low for the Compton opacity (almost at the Thomson limit), though it might not matter in this case.

2024-08-06 11:50 UTC, afloers commented
Just added some minor comments, other than that the PR looks good to me