Minor refactor of the spectrum solver
tardis-sn/tardis pull request #2759
Opened 2024-07-29 20:11 UTC by andrewfullard

### :pencil: Description

**Type:** :roller_coaster: `infrastructure`

Adjustment to the spectrum solver to consolidate property assignments and factor out luminosity integration calculations (which do not use anything relevant from the spectrum solver).

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

2024-07-29 20:15 UTC, andrewfullard commented on tardis/spectrum/luminosity.py
> +def calculate_emitted_luminosity(
Could maybe become a solver class if we want to be extra about it.

2024-07-29 20:16 UTC, Rodot- requested changes
I think tests for these functions are needed, will approve once added

2024-07-29 20:16 UTC, Rodot- commented on tardis/spectrum/luminosity.py
> +def calculate_emitted_luminosity(
Are these covered by tests?

2024-08-06 17:28 UTC, Rodot- approved these changes
This all looks good to merge for me

2024-08-09 17:51 UTC, wkerzendorf approved these changes

2024-08-09 17:59 UTC, merged