Gammaray opacity documentation
tardis-sn/tardis pull request #2876
Opened 2024-11-12 14:13 UTC by CePowers

### :pencil: Description

**Type:** :memo: `documentation` `

I started a new documentation file for the sources of opacity for gamma rays. I added information for Compton Scattering with plans to add other sources of opacity.

### :pushpin: Resources

Examples, notebooks, and links to useful references.

### :vertical_traffic_light: Testing

How did you test these changes?

- [ ] Testing pipeline
- [ ] Other method (describe)
- [ ] My changes can't be tested (explain why)

### :ballot_box_with_check: Checklist

- [ ] I requested two reviewers for this pull request
- [ ] I updated the documentation according to my changes
- [ ] I built the documentation by applying the `build_docs` label

> **Note:** If you are not allowed to perform any of these actions, ping (@) a contributor.

2024-12-02 15:16 UTC, andrewfullard requested changes
Would like to see units on the y-axis of each plot

2024-12-02 15:16 UTC, andrewfullard commented on docs/physics/tardisgamma/opacities.rst
> +    \alpha_{pp}(h\nu \geq 1.5) = \rho [ \frac{Z_{\text{Si}}^2}{m_{\text{Si}}} (1 - X_{\text{IGE}}) + \frac{Z_{\text{Fe}}^2}{m_{\text{Fe}}} X_{\text{IGE}}] [0.481 + 0.301(h\nu - 1.5) \times 10^{-27}
Missing brackets in this equation

2024-12-02 15:18 UTC, jvshields commented on docs/physics/tardisgamma/opacities.rst
> +The coefficient is:
Missing a period before this line.

2024-12-02 15:19 UTC, jvshields commented
I think that this would be a lot more informative if all the different opacities were plotted together so you could more easily compare which opacity matters in which range. The text is fine and looks good, but I would definitely like to see the plots merged.

2024-12-09 15:13 UTC, andrewfullard commented on docs/physics/tardisgamma/images/all_coeffs.png
The Total line being yellow is very difficult to read on white. I would also recommend using colourblind-safe colours for all lines.

2024-12-09 15:14 UTC, andrewfullard commented on docs/physics/tardisgamma/images/all_coeffs.png
It would also be reasonable to limit the axes to cover the interesting region where all 3 opacities cross.

2024-12-09 15:15 UTC, andrewfullard commented on docs/physics/tardisgamma/images/coeff_fractions.png
I don't think the y-axis needs to be logarithmic here

2025-02-03 15:24 UTC, jvshields commented on docs/physics/tardisgamma/opacities.ipynb
> +{
<pre class="ql-syntax" spellcheck="false">Line #13.    plt.ylabel("Opacity (cm^-1)")
</pre><p>To make this look right, you want to do plt.ylabel(f"Opacity (cm$^{-1}$))</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/tardis-sn/tardis/pull/2876/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='7'/>

2025-02-21 15:39 UTC, wkerzendorf commented
very nice. Please add some citations and we might want to shift the formulas around in the opacities notebook. @Knights-Templars will know!

2025-02-27 21:45 UTC, Knights-Templars commented
The citations still don't work. Also, please add citations for other opacities also (photo-absorption, compton).

2025-03-28 16:02 UTC, andrewfullard submitted a review, later dismissed

2025-03-31 14:47 UTC, wkerzendorf commented on docs/physics/tardisgamma/opacities.ipynb
> +{
<p>please add a link to what equation it is in the papers. Also please add units to the formula</p><p> </p>
<br/>

 _Reply via <a href='https://app.reviewnb.com/tardis-sn/tardis/pull/2876/discussion/'>ReviewNB</a>_ <div id='ReviewNBCommentContext-DoNotDelete' style='display:none' data-state='OPEN' data-cellIndex='5'/>

2025-04-03 14:05 UTC, andrewfullard submitted a review, later dismissed

2025-04-03 14:16 UTC, jvshields commented
Looks great, but the Ambwani1988 is still broken.

2025-04-04 13:13 UTC, andrewfullard approved these changes

2025-04-04 14:03 UTC, jvshields approved these changes

2025-04-04 14:03 UTC, merged